config/routes.rb
Transfair::Application.routes.draw do
  get "dropbox/index"
  get "dropbox/upload"
  post "dropbox/upload"
  get "dropbox/authorize"
  match 'db/authorize', :controller => 'db', :action => 'authorize'
  match 'db/upload', :controller => 'db', :action => 'upload'

  resources :transcription_informations

  resources :spotchecks

  resources :fields

  resources :affiliations

  mount WillFilter::Engine => "/will_filter"
    
  devise_for :users, :path_names => {:sign_up => "register"}

  resources :service_partners

  resources :fair_wages

  resources :countries

  resources :languages

  resources :jobs

  resources :job_statuses

  resources :job_types

  resources :clients

  root :to => 'clients#index'

end

app/models/spotcheck.rb
class Spotcheck < ActiveRecord::Base
  belongs_to :job
  belongs_to :service_partner

  # TODO: Do we need anything accessible here? I think this gets all just set
  #       by program logic – or am I wrong?
  attr_accessible :job_id, :job,
                  :service_partner_id, :service_partner
                  # :rating,
                  # :rating_text
end

app/controllers/spotchecks_controller.rb
class SpotchecksController < ApplicationController
  # GET /spotchecks
  # GET /spotchecks.json
  def index
    @spotchecks = Spotcheck.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spotchecks }
    end
  end

  # GET /spotchecks/1
  # GET /spotchecks/1.json
  def show
    @spotcheck = Spotcheck.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spotcheck }
    end
  end

  # GET /spotchecks/new
  # GET /spotchecks/new.json
  def new
    @spotcheck = Spotcheck.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spotcheck }
    end
  end

  # GET /spotchecks/1/edit
  def edit
    @spotcheck = Spotcheck.find(params[:id])
  end

  # POST /spotchecks
  # POST /spotchecks.json
  def create
    @spotcheck = Spotcheck.new(params[:spotcheck])

    respond_to do |format|
      if @spotcheck.save
        format.html { redirect_to @spotcheck, notice: 'Spotcheck was successfully created.' }
        format.json { render json: @spotcheck, status: :created, location: @spotcheck }
      else
        format.html { render action: "new" }
        format.json { render json: @spotcheck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spotchecks/1
  # PUT /spotchecks/1.json
  def update
    @spotcheck = Spotcheck.find(params[:id])

    respond_to do |format|
      if @spotcheck.update_attributes(params[:spotcheck])
        format.html { redirect_to @spotcheck, notice: 'Spotcheck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spotcheck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spotchecks/1
  # DELETE /spotchecks/1.json
  def destroy
    @spotcheck = Spotcheck.find(params[:id])
    @spotcheck.destroy

    respond_to do |format|
      format.html { redirect_to spotchecks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/spotchecks_helper.rb
module SpotchecksHelper
end

app/views/spotchecks/_form.html.erb
<%= form_for(@spotcheck) do |f| %>
  <% if @spotcheck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spotcheck.errors.length, "error") %> prohibited this spotcheck from being saved:</h2>

      <ul>
      <% @spotcheck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_id %><br />
    <%= f.number_field :job_id %>
  </div>
  <div class="field">
    <%= f.label :service_partner_id %><br />
    <%= f.number_field :service_partner_id %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :rating_text %><br />
    <%= f.text_area :rating_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spotchecks/edit.html.erb
<h1>Editing spotcheck</h1>

<%= render 'form' %>

<%= link_to 'Show', @spotcheck %> |
<%= link_to 'Back', spotchecks_path %>

app/views/spotchecks/index.html.erb
<h1>Listing spotchecks</h1>

<table>
  <tr>
    <th>Job</th>
    <th>Service partner</th>
    <th>Rating</th>
    <th>Rating text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spotchecks.each do |spotcheck| %>
  <tr>
    <td><%= spotcheck.job_id %></td>
    <td><%= spotcheck.service_partner_id %></td>
    <td><%= spotcheck.rating %></td>
    <td><%= spotcheck.rating_text %></td>
    <td><%= link_to 'Show', spotcheck %></td>
    <td><%= link_to 'Edit', edit_spotcheck_path(spotcheck) %></td>
    <td><%= link_to 'Delete', spotcheck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Spotcheck', new_spotcheck_path %>

app/views/spotchecks/new.html.erb
<h1>New spotcheck</h1>

<%= render 'form' %>

<%= link_to 'Back', spotchecks_path %>

app/views/spotchecks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Job:</b>
  <%= @spotcheck.job_id %>
</p>

<p>
  <b>Service partner:</b>
  <%= @spotcheck.service_partner_id %>
</p>

<p>
  <b>Rating:</b>
  <%= @spotcheck.rating %>
</p>

<p>
  <b>Rating text:</b>
  <%= @spotcheck.rating_text %>
</p>


<%= link_to 'Edit', edit_spotcheck_path(@spotcheck) %> |
<%= link_to 'Back', spotchecks_path %>