config/routes.rb
Transfair::Application.routes.draw do
  get "dropbox/index"
  get "dropbox/upload"
  post "dropbox/upload"
  get "dropbox/authorize"
  match 'db/authorize', :controller => 'db', :action => 'authorize'
  match 'db/upload', :controller => 'db', :action => 'upload'

  resources :transcription_informations

  resources :spotchecks

  resources :fields

  resources :affiliations

  mount WillFilter::Engine => "/will_filter"
    
  devise_for :users, :path_names => {:sign_up => "register"}

  resources :service_partners

  resources :fair_wages

  resources :countries

  resources :languages

  resources :jobs

  resources :job_statuses

  resources :job_types

  resources :clients

  root :to => 'clients#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :client
  belongs_to :job_type
  belongs_to :job_status
  belongs_to :language
  belongs_to :transcription_information
  has_many :employments
  has_many :service_partners, :through => :employments

  attr_accessible :name,
                  :client_id, :client,
                  :deadline_client,
                  # :deadline_intern,
                  :job_type_id, :job_type,
                  # :job_status_id,
                  # :client_paid,
                  # :rating_client,
                  # :rating_text,
                  # :special_price,
                  :language_id, :language,
                  :trancription_information_id, :trancription_information

  validates :name, :presence => true
  #validates :client_id, :presence => true      #automatically set when new job
  validates :deadline_client, :presence => true
  #validates :deadline_client, :date => {:after => Time.now}
  #validates :deadline_intern, :date => {:after => Time.now}
  #validates :job_status_id, :presence => true

 # def init
  #  self.status ||= JobStatus.first
  #end

end

app/models/job_type.rb
class JobType < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for @job, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :deadline_client, :as => :date %>
  <%= f.input :job_type_id, :collection => JobType.all.collect { |p| [ p.name , p.id ] } %>
  <%= f.button :submit %>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<%- model_class = Job -%>
<div class="page-header">
    <h1>
    <%=t '.title', :default => model_class.model_name.human.pluralize %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
            new_job_path,
            :class => 'btn btn-primary btn-in-heading' %> 
  </h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:clients) %></th>
      <th><%= model_class.human_attribute_name(:service_partners) %></th>
      <th><%= model_class.human_attribute_name(:deadline_client) %></th>
      <th><%= model_class.human_attribute_name(:deadline_intern) %></th>
      <th><%= model_class.human_attribute_name(:job_type) %></th>
      <th><%= model_class.human_attribute_name(:job_status) %></th>
      <th><%= model_class.human_attribute_name(:client_paid) %></th>
      <th><%= model_class.human_attribute_name(:rating_client) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.name, job_path(job) %></td>

        <% if job.client.nil? %>
          <td><%= '' %></td>
        <% else %>
          <td><%= link_to job.client.full_name, client_path(job.client) %></td>
        <% end %>

        <td>
          <% job.service_partners.each do |sp| %>
            <%= link_to sp.full_name, service_partner_path(sp) %><br/>
          <%end%>
        </td>

        <% if job.deadline_client.nil? %>
          <td><%= '' %></td>
        <% else %>
          <td><%= job.deadline_client.to_date.strftime("%d %b") %></td>
        <% end %>

        <% if job.deadline_intern.nil? %>
          <td><%= '' %></td>
        <% else %>
          <td><%= job.deadline_intern.to_date.strftime("%d %b")  %></td>
        <% end %>

        <% if job.job_type.nil? %>
          <td><%= '' %></td>
        <% else %>
          <td><%= job.job_type.name %></td>
        <% end %>

        <% if job.job_status.nil? %>
          <td><%= '' %></td>
        <% else %>
          <td><%= job.job_status.name %></td>
        <% end %>

        <td><%= job.client_paid %></td>
        <td><%= job.rating_client %></td>
        <td><%=l job.created_at, :format => :short %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.delete', :default => t("helpers.links.delete")),
                      job_path(job),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/show.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl> <%# dl-horizontal did not work fine with empty fields #%>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @job.name %></dd>

  <dt><strong><%= model_class.human_attribute_name(:client_name) %>:</strong></dt>
  <% if @job.client == nil %>
    <dd><%= '' %></dd>
  <% else %>
    <dd><%= @job.client.full_name %></dd>
  <% end %>

  <dt><strong><%= model_class.human_attribute_name(:deadline_client) %>:</strong></dt>
  <dd><%= @job.deadline_client %></dd>

  <dt><strong><%= model_class.human_attribute_name(:deadline_intern) %>:</strong></dt>
  <dd><%= @job.deadline_intern %></dd>

  <dt><strong><%= model_class.human_attribute_name(:job_type) %>:</strong></dt>
  <% if @job.job_type == nil %>
    <dd><%= '' %></dd>
  <% else %>
    <dd><%= @job.job_type.name %></dd>
  <% end %>

  <dt><strong><%= model_class.human_attribute_name(:job_status) %>:</strong></dt>
  <% if @job.job_status == nil %>
    <dd><%= '' %></dd>
  <% else %>
    <dd><%= @job.job_status.name %></dd>
  <% end %>

  <dt><strong><%= model_class.human_attribute_name(:client_paid) %>:</strong></dt>
  <dd><%= @job.client_paid %></dd>

  <dt><strong><%= model_class.human_attribute_name(:rating_client) %>:</strong></dt>
  <dd><%= @job.rating_client %></dd>

  <dt><strong><%= model_class.human_attribute_name(:rating_text) %>:</strong></dt>
  <dd><%= @job.rating_text %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              jobs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_job_path(@job), :class => 'btn' %>
  <%= link_to t('.delete', :default => t("helpers.links.delete")),
              job_path(@job),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>