config/routes.rb
Transfair::Application.routes.draw do
  get "dropbox/index"
  get "dropbox/upload"
  post "dropbox/upload"
  get "dropbox/authorize"
  match 'db/authorize', :controller => 'db', :action => 'authorize'
  match 'db/upload', :controller => 'db', :action => 'upload'

  resources :transcription_informations

  resources :spotchecks

  resources :fields

  resources :affiliations

  mount WillFilter::Engine => "/will_filter"
    
  devise_for :users, :path_names => {:sign_up => "register"}

  resources :service_partners

  resources :fair_wages

  resources :countries

  resources :languages

  resources :jobs

  resources :job_statuses

  resources :job_types

  resources :clients

  root :to => 'clients#index'

end

app/models/affiliation.rb
class Affiliation < ActiveRecord::Base
  has_many :users

  attr_accessible :name
end

app/controllers/affiliations_controller.rb
class AffiliationsController < ApplicationController
  # GET /affiliations
  # GET /affiliations.json
  def index
    @affiliations = Affiliation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @affiliations }
    end
  end

  # GET /affiliations/1
  # GET /affiliations/1.json
  def show
    @affiliation = Affiliation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @affiliation }
    end
  end

  # GET /affiliations/new
  # GET /affiliations/new.json
  def new
    @affiliation = Affiliation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @affiliation }
    end
  end

  # GET /affiliations/1/edit
  def edit
    @affiliation = Affiliation.find(params[:id])
  end

  # POST /affiliations
  # POST /affiliations.json
  def create
    @affiliation = Affiliation.new(params[:affiliation])

    respond_to do |format|
      if @affiliation.save
        format.html { redirect_to @affiliation, notice: 'Affiliation was successfully created.' }
        format.json { render json: @affiliation, status: :created, location: @affiliation }
      else
        format.html { render action: "new" }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /affiliations/1
  # PUT /affiliations/1.json
  def update
    @affiliation = Affiliation.find(params[:id])

    respond_to do |format|
      if @affiliation.update_attributes(params[:affiliation])
        format.html { redirect_to @affiliation, notice: 'Affiliation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affiliations/1
  # DELETE /affiliations/1.json
  def destroy
    @affiliation = Affiliation.find(params[:id])
    @affiliation.destroy

    respond_to do |format|
      format.html { redirect_to affiliations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/affiliations_helper.rb
module AffiliationsHelper
end

app/views/affiliations/_form.html.erb
<%= form_for(@affiliation) do |f| %>
  <% if @affiliation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@affiliation.errors.count, "error") %> prohibited this affiliation from being saved:</h2>

      <ul>
      <% @affiliation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/affiliations/edit.html.erb
<h1>Editing affiliation</h1>

<%= render 'form' %>

<%= link_to 'Show', @affiliation %> |
<%= link_to 'Back', affiliations_path %>

app/views/affiliations/index.html.erb
<h1>Listing affiliations</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @affiliations.each do |affiliation| %>
  <tr>
    <td><%= affiliation.name %></td>
    <td><%= link_to 'Show', affiliation %></td>
    <td><%= link_to 'Edit', edit_affiliation_path(affiliation) %></td>
    <td><%= link_to 'Delete', affiliation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Affiliation', new_affiliation_path %>

app/views/affiliations/new.html.erb
<h1>New affiliation</h1>

<%= render 'form' %>

<%= link_to 'Back', affiliations_path %>

app/views/affiliations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @affiliation.name %>
</p>


<%= link_to 'Edit', edit_affiliation_path(@affiliation) %> |
<%= link_to 'Back', affiliations_path %>